### ISSUE TITLE
Performance can be improved

### ISSUE THREAD

**Issue by qgustavor** [qgustavor/mkv-extract#1]
Seems the tool has a bad performance considering it's only demuxing the file. Can it can be improved? How? Web Workers maybe?

**Comment by qgustavor** [comment]
Closing as no progress was made.

**Comment by pawitp** [comment]
The slow performance is due to node-ebml generating debug strings even though it is not used. This is very slow on the Buffer shim used by browserify.

The performance will be greatly improved once https://github.com/themasch/node-ebml/pull/37 is merged.

**Comment by themasch** [comment]
just merged it. Thanks for the contribution! 
I hope to be able to release 3.0 later this week. Maybe releasing a (at)next version prior to the public release so early adopters can do their tests. 
[edit:]
Just released 2.2.4 containing this patch. Happy decoding!

**Comment by qgustavor** [comment]
Just updated it: I'm impressed with the results.

**Comment by pawitp** [comment]
Glad to be of help! :)

For the record, I found this out by running Chrome's Profiler (F12 Performance Tab) and noticed that most of the time was spent doing the toString() call.

And a bit of self-promo, I'm using this code to make https://github.com/pawitp/mkv-player which uses the JS File API to extract the .ass file then pass it into https://github.com/Dador/JavascriptSubtitlesOctopus (emscriptem'ed libass) to decode and render subtitles right inside the browser.
