### ISSUE TITLE
How to extract SRT subtitles 

### ISSUE THREAD

**Issue by anhthoai** [qgustavor/mkv-extract#24]
Hello. I test and see that script extract ass files only. Do you have any way to extract SRT files?
Thank you.

**Comment by qgustavor** [comment]
It handles SRT: https://github.com/qgustavor/mkv-extract/blob/850b8a74bb24145d692df7ee95578488c9684a85/src/main.ts#L211

I just tested with a file I have here, it managed to extract all subtitles from it without any issue.

**Comment by qgustavor** [comment]
If you think your video indeed have SRT subtitles and that's a bug of this tool, post the output of MediaInfo below. There is an online version of it: https://mediaarea.net/MediaInfoOnline

**Comment by qgustavor** [comment]
Closing as I cannot reproduce. If you can provide more info about the video which is not working just comment. Even if you have videos which the current code cannot handle I think it will be fixed when #21 gets solved.

**Comment by anhthoai** [comment]
Hello. Could you please name subtitle like "original file name"_{lang_code}.ass/srt? Like testing_en.srt. That will be easy for understanding.

**Comment by qgustavor** [comment]
That's planned for after #21 gets solved.
