### ISSUE TITLE
WEB Tool doesn't work... (https://qgustavor.github.io/mkv-extract/en/)

### ISSUE THREAD

**Issue by Iluvatar77** [qgustavor/mkv-extract#43]
Hi!

It seems like the website doesn't work anymore.. I receive the same error message in both Firefox and Chrome:

"Undefined. Could not load the file"

Can you please check and see if something has happened?

Love your work!

**Comment by qgustavor** [comment]
Could not reproduce. Can you provide more information, please?

**Comment by Iluvatar77** [comment]
<img width="1194" alt="Skärmavbild 2024-06-04 kl  19 21 08" src="https://github.com/qgustavor/mkv-extract/assets/124593668/53cc7a3f-3a78-49c3-9677-05bf75772ffc">

The drag and drop function seems to be the problem. It works when pressing "Click or drop files here to extract" and uploading the file. But drag and drop isn't working. Tried several solutions and restarts etc...

Mac user.

**Comment by qgustavor** [comment]
Seems the fix for #31 was buggy. I'll look into that, IIRC I only tested it by clicking.

**Comment by qgustavor** [comment]
I fixed it, it was missing a simple "..." in the code. 😓

**Comment by Iluvatar77** [comment]
Awesome! Now it works as before. Keep up the great work!
